browser=chrome
headless=false
timeout=10
environment=dev

base_url=https://automatisvsonexercise.com

login_url=/login
signup_url=/login
products_url=/products
cart_url=/view_cart

excel_path=src/test/resources/testdata/Testdata.xlsx
csv_path=testdata/TestdataCSV.csv