get_all_products=SELECT * FROM products

get_product_by_id=SELECT * FROM products WHERE id = ?

get_product_by_name=SELECT * FROM products WHERE product_name = ?

get_user_by_email=SELECT * FROM users WHERE email = ?

insert_product=INSERT INTO products (product_name, price) VALUES (?, ?)

update_product=UPDATE products SET price = ? WHERE id = ?

delete_product=DELETE FROM products WHERE id = ?